nginx:
    environment:
        - VIRTUAL_HOST=project-a
        - NGINX_HOST=project-a
        - NGINX_PORT=80
    image: nginx
    ports:
        - 8081:80
    volumes:
        - ./web:/usr/share/nginx/html:ro
